substitutions:
  device_name: "Toshiba AC Example"

esphome:
  name: toshiba-ac-example
  platform: ESP8266
  board: esp12e

logger:
  level: DEBUG

external_components:
  - source: ./components

status_led:
  pin:
    number: GPIO2
    inverted: true

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 2400
  parity: EVEN

climate:
  - platform: tcc_link
    name: "${device_name}"
    id: toshiba_ac
    connected:
      name: "${device_name} Connected"
    failed_crcs:
      name: "${device_name} Failed CRCs"
    vent:
      name: "${device_name} Vent"
    on_data_received:
      - lambda: |-
          ESP_LOGD("TCC", "Data received: %d bytes", x.size());